name: Release Build and Deploy

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., v1.0.0)'
        required: true
        type: string
      prerelease:
        description: 'Mark as pre-release'
        required: false
        default: false
        type: boolean

permissions:
  contents: write
  packages: write
  actions: read
  security-events: write

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-deploy:
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'macos-latest'
            args: '--target aarch64-apple-darwin'
            target: 'aarch64-apple-darwin'
            arch: 'arm64'
          - platform: 'macos-latest'
            args: '--target x86_64-apple-darwin'
            target: 'x86_64-apple-darwin'
            arch: 'x64'
          - platform: 'ubuntu-22.04'
            args: ''
            target: 'x86_64-unknown-linux-gnu'
            arch: 'x64'
          - platform: 'windows-latest'
            args: ''
            target: 'x86_64-pc-windows-msvc'
            arch: 'x64'

    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.0-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Rust setup
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'

      - name: Install frontend dependencies
        run: yarn install --frozen-lockfile

      - name: Build the app
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
        with:
          tagName: ${{ github.event_name == 'workflow_dispatch' && inputs.version || github.ref_name }}
          releaseName: "PlanIt ${{ github.event_name == 'workflow_dispatch' && inputs.version || github.ref_name }}"
          releaseBody: "See the assets to download and install this version."
          releaseDraft: false
          prerelease: ${{ github.event_name == 'workflow_dispatch' && inputs.prerelease || false }}
          args: ${{ matrix.args }}

      - name: Upload to Cloudflare R2 (Unix)
        if: matrix.platform != 'windows-latest'
        env:
          CLOUDFLARE_R2_ACCESS_KEY_ID: ${{ secrets.CLOUDFLARE_R2_ACCESS_KEY_ID }}
          CLOUDFLARE_R2_SECRET_ACCESS_KEY: ${{ secrets.CLOUDFLARE_R2_SECRET_ACCESS_KEY }}
          CLOUDFLARE_R2_BUCKET: ${{ secrets.CLOUDFLARE_R2_BUCKET }}
          CLOUDFLARE_R2_ENDPOINT: ${{ secrets.CLOUDFLARE_R2_ENDPOINT }}
        run: |
          # Install AWS CLI for S3-compatible operations
          if [[ "${{ matrix.platform }}" == "ubuntu-22.04" ]]; then
            sudo apt-get install -y awscli
          elif [[ "${{ matrix.platform }}" == "macos-latest" ]]; then
            brew install awscli
          fi
          
          # Configure AWS CLI for R2
          aws configure set aws_access_key_id $CLOUDFLARE_R2_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $CLOUDFLARE_R2_SECRET_ACCESS_KEY
          aws configure set region auto
          
          # Upload build artifacts to R2
          VERSION=${{ github.event_name == 'workflow_dispatch' && inputs.version || github.ref_name }}
          PLATFORM_NAME=""
          
          if [[ "${{ matrix.platform }}" == "ubuntu-22.04" ]]; then
            PLATFORM_NAME="linux"
          elif [[ "${{ matrix.platform }}" == "macos-latest" ]]; then
            if [[ "${{ matrix.arch }}" == "arm64" ]]; then
              PLATFORM_NAME="darwin-aarch64"
            else
              PLATFORM_NAME="darwin-x64"
            fi
          fi
          
          # Find and upload build artifacts
          if [[ "${{ matrix.platform }}" == "ubuntu-22.04" ]]; then
            find src-tauri/target/${{ matrix.target }}/release/bundle -name "*.deb" -o -name "*.AppImage" | while read file; do
              filename=$(basename "$file")
              aws s3 cp "$file" "s3://$CLOUDFLARE_R2_BUCKET/releases/$VERSION/$PLATFORM_NAME/$filename" --endpoint-url="$CLOUDFLARE_R2_ENDPOINT"
              echo "Uploaded: $filename to releases/$VERSION/$PLATFORM_NAME/"
            done
          elif [[ "${{ matrix.platform }}" == "macos-latest" ]]; then
            find src-tauri/target/${{ matrix.target }}/release/bundle -name "*.dmg" | while read file; do
              filename=$(basename "$file")
              aws s3 cp "$file" "s3://$CLOUDFLARE_R2_BUCKET/releases/$VERSION/$PLATFORM_NAME/$filename" --endpoint-url="$CLOUDFLARE_R2_ENDPOINT"
              echo "Uploaded: $filename to releases/$VERSION/$PLATFORM_NAME/"
            done
          fi
          
          # Upload updater files if they exist
          if [[ -f "src-tauri/target/${{ matrix.target }}/release/bundle/updater/latest.json" ]]; then
            aws s3 cp "src-tauri/target/${{ matrix.target }}/release/bundle/updater/latest.json" "s3://$CLOUDFLARE_R2_BUCKET/updates/latest.json" --endpoint-url="$CLOUDFLARE_R2_ENDPOINT"
            echo "Uploaded updater manifest"
          fi
          
          # Upload signature files
          find src-tauri/target/${{ matrix.target }}/release/bundle -name "*.sig" | while read file; do
            filename=$(basename "$file")
            aws s3 cp "$file" "s3://$CLOUDFLARE_R2_BUCKET/releases/$VERSION/$PLATFORM_NAME/$filename" --endpoint-url="$CLOUDFLARE_R2_ENDPOINT"
            echo "Uploaded signature: $filename"
          done

      - name: Upload to Cloudflare R2 (Windows)
        if: matrix.platform == 'windows-latest'
        env:
          CLOUDFLARE_R2_ACCESS_KEY_ID: ${{ secrets.CLOUDFLARE_R2_ACCESS_KEY_ID }}
          CLOUDFLARE_R2_SECRET_ACCESS_KEY: ${{ secrets.CLOUDFLARE_R2_SECRET_ACCESS_KEY }}
          CLOUDFLARE_R2_BUCKET: ${{ secrets.CLOUDFLARE_R2_BUCKET }}
          CLOUDFLARE_R2_ENDPOINT: ${{ secrets.CLOUDFLARE_R2_ENDPOINT }}
        shell: pwsh
        run: |
          # Install AWS CLI for S3-compatible operations
          choco install awscli -y
          
          # Configure AWS CLI for R2
          aws configure set aws_access_key_id $env:CLOUDFLARE_R2_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $env:CLOUDFLARE_R2_SECRET_ACCESS_KEY
          aws configure set region auto
          
          # Upload build artifacts to R2
          $VERSION = "${{ github.event_name == 'workflow_dispatch' && inputs.version || github.ref_name }}"
          $PLATFORM_NAME = "windows"
          
          # Debug: List the target directory structure
          Write-Host "Listing target directory structure:"
          if (Test-Path "src-tauri/target/${{ matrix.target }}/release/bundle") {
            Get-ChildItem -Path "src-tauri/target/${{ matrix.target }}/release/bundle" -Recurse | ForEach-Object {
              Write-Host $_.FullName
            }
          } else {
            Write-Host "Bundle directory not found at src-tauri/target/${{ matrix.target }}/release/bundle"
          }
          
          # Find and upload MSI files
          $msiPath = "src-tauri/target/${{ matrix.target }}/release/bundle/msi"
          if (Test-Path $msiPath) {
            Get-ChildItem -Path $msiPath -Include "*.msi" | ForEach-Object {
              $filename = $_.Name
              aws s3 cp $_.FullName "s3://$env:CLOUDFLARE_R2_BUCKET/releases/$VERSION/$PLATFORM_NAME/$filename" --endpoint-url="$env:CLOUDFLARE_R2_ENDPOINT"
              Write-Host "Uploaded MSI: $filename to releases/$VERSION/$PLATFORM_NAME/"
            }
          }
          
          # Find and upload NSIS files
          $nsisPath = "src-tauri/target/${{ matrix.target }}/release/bundle/nsis"
          if (Test-Path $nsisPath) {
            Get-ChildItem -Path $nsisPath -Include "*.exe" | ForEach-Object {
              $filename = $_.Name
              aws s3 cp $_.FullName "s3://$env:CLOUDFLARE_R2_BUCKET/releases/$VERSION/$PLATFORM_NAME/$filename" --endpoint-url="$env:CLOUDFLARE_R2_ENDPOINT"
              Write-Host "Uploaded NSIS: $filename to releases/$VERSION/$PLATFORM_NAME/"
            }
          }
          
          # Upload updater files if they exist
          $updaterFile = "src-tauri/target/${{ matrix.target }}/release/bundle/updater/latest.json"
          if (Test-Path $updaterFile) {
            aws s3 cp $updaterFile "s3://$env:CLOUDFLARE_R2_BUCKET/updates/latest.json" --endpoint-url="$env:CLOUDFLARE_R2_ENDPOINT"
            Write-Host "Uploaded updater manifest"
          }
          
          # Upload signature files from MSI directory
          if (Test-Path $msiPath) {
            Get-ChildItem -Path $msiPath -Include "*.sig" | ForEach-Object {
              $filename = $_.Name
              aws s3 cp $_.FullName "s3://$env:CLOUDFLARE_R2_BUCKET/releases/$VERSION/$PLATFORM_NAME/$filename" --endpoint-url="$env:CLOUDFLARE_R2_ENDPOINT"
              Write-Host "Uploaded MSI signature: $filename"
            }
          }
          
          # Upload signature files from NSIS directory
          if (Test-Path $nsisPath) {
            Get-ChildItem -Path $nsisPath -Include "*.sig" | ForEach-Object {
              $filename = $_.Name
              aws s3 cp $_.FullName "s3://$env:CLOUDFLARE_R2_BUCKET/releases/$VERSION/$PLATFORM_NAME/$filename" --endpoint-url="$env:CLOUDFLARE_R2_ENDPOINT"
              Write-Host "Uploaded NSIS signature: $filename"
            }
          }

  create-release-manifest:
    needs: build-and-deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create release manifest
        env:
          CLOUDFLARE_R2_ACCESS_KEY_ID: ${{ secrets.CLOUDFLARE_R2_ACCESS_KEY_ID }}
          CLOUDFLARE_R2_SECRET_ACCESS_KEY: ${{ secrets.CLOUDFLARE_R2_SECRET_ACCESS_KEY }}
          CLOUDFLARE_R2_BUCKET: ${{ secrets.CLOUDFLARE_R2_BUCKET }}
          CLOUDFLARE_R2_ENDPOINT: ${{ secrets.CLOUDFLARE_R2_ENDPOINT }}
        run: |
          # Update package list and install dependencies
          sudo apt-get update
          sudo apt-get install -y jq curl unzip
          
          # Install or update AWS CLI v2 using the official installer
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          # Check if AWS CLI is already installed and use --update flag if needed
          if [ -d "/usr/local/aws-cli" ]; then
            sudo ./aws/install --update
          else
            sudo ./aws/install
          fi
          
          # Configure AWS CLI for R2
          aws configure set aws_access_key_id $CLOUDFLARE_R2_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $CLOUDFLARE_R2_SECRET_ACCESS_KEY
          aws configure set region auto
          
          VERSION=${{ github.event_name == 'workflow_dispatch' && inputs.version || github.ref_name }}
          
          # Create release manifest
          cat > release-manifest.json << EOF
          {
            "version": "$VERSION",
            "pub_date": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
            "platforms": {
              "linux-x86_64": {
                "signature": "",
                "url": "https://oss.ttata.com/releases/$VERSION/linux/"
              },
              "darwin-x86_64": {
                "signature": "",
                "url": "https://oss.ttata.com/releases/$VERSION/darwin-x64/"
              },
              "darwin-aarch64": {
                "signature": "",
                "url": "https://oss.ttata.com/releases/$VERSION/darwin-aarch64/"
              },
              "windows-x86_64": {
                "signature": "",
                "url": "https://oss.ttata.com/releases/$VERSION/windows/"
              }
            }
          }
          EOF
          
          # Upload release manifest
          aws s3 cp release-manifest.json "s3://$CLOUDFLARE_R2_BUCKET/releases/$VERSION/manifest.json" --endpoint-url="$CLOUDFLARE_R2_ENDPOINT"
          echo "Release manifest created and uploaded"
          
          # Create latest.json for updater with proper format
          # Get app name from Cargo.toml
          APP_NAME=$(grep '^name = ' src-tauri/Cargo.toml | sed 's/name = "\(.*\)"/\1/')
          
          # Function to get signature from R2
          get_signature() {
            local platform=$1
            local file_pattern=$2
            
            # Try to download and read signature file
            local sig_file=$(aws s3 ls "s3://$CLOUDFLARE_R2_BUCKET/releases/$VERSION/$platform/" --endpoint-url="$CLOUDFLARE_R2_ENDPOINT" | grep "\.sig$" | grep "$file_pattern" | awk '{print $4}' | head -1)
            if [ ! -z "$sig_file" ]; then
              aws s3 cp "s3://$CLOUDFLARE_R2_BUCKET/releases/$VERSION/$platform/$sig_file" "/tmp/$sig_file" --endpoint-url="$CLOUDFLARE_R2_ENDPOINT" 2>/dev/null
              if [ -f "/tmp/$sig_file" ]; then
                cat "/tmp/$sig_file"
                rm "/tmp/$sig_file"
              fi
            fi
          }
          
          # Get actual file names and signatures
          LINUX_FILE=$(aws s3 ls "s3://$CLOUDFLARE_R2_BUCKET/releases/$VERSION/linux/" --endpoint-url="$CLOUDFLARE_R2_ENDPOINT" | grep "\.AppImage$" | awk '{print $4}' | head -1)
          LINUX_SIG=$(get_signature "linux" "AppImage")
          
          DARWIN_X64_FILE=$(aws s3 ls "s3://$CLOUDFLARE_R2_BUCKET/releases/$VERSION/darwin-x64/" --endpoint-url="$CLOUDFLARE_R2_ENDPOINT" | grep "\.dmg$" | awk '{print $4}' | head -1)
          DARWIN_X64_SIG=$(get_signature "darwin-x64" "dmg")
          
          DARWIN_AARCH64_FILE=$(aws s3 ls "s3://$CLOUDFLARE_R2_BUCKET/releases/$VERSION/darwin-aarch64/" --endpoint-url="$CLOUDFLARE_R2_ENDPOINT" | grep "\.dmg$" | awk '{print $4}' | head -1)
          DARWIN_AARCH64_SIG=$(get_signature "darwin-aarch64" "dmg")
          
          WINDOWS_MSI_FILE=$(aws s3 ls "s3://$CLOUDFLARE_R2_BUCKET/releases/$VERSION/windows/" --endpoint-url="$CLOUDFLARE_R2_ENDPOINT" | grep "\.msi$" | awk '{print $4}' | head -1)
          WINDOWS_MSI_SIG=$(get_signature "windows" "msi")
          
          WINDOWS_EXE_FILE=$(aws s3 ls "s3://$CLOUDFLARE_R2_BUCKET/releases/$VERSION/windows/" --endpoint-url="$CLOUDFLARE_R2_ENDPOINT" | grep "\.exe$" | awk '{print $4}' | head -1)
          WINDOWS_EXE_SIG=$(get_signature "windows" "exe")
          
          # Create latest.json with proper Tauri updater format
          cat > latest.json << EOF
          {
            "version": "$VERSION",
            "notes": "Release $VERSION",
            "pub_date": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
            "platforms": {
          EOF
          
          # Add Linux platform if file exists
          if [ ! -z "$LINUX_FILE" ]; then
            cat >> latest.json << EOF
              "linux-x86_64": {
                "signature": "${LINUX_SIG:-""}",
                "url": "https://oss.ttata.com/releases/$VERSION/linux/$LINUX_FILE"
              },
          EOF
          fi
          
          # Add macOS x64 platform if file exists
          if [ ! -z "$DARWIN_X64_FILE" ]; then
            cat >> latest.json << EOF
              "darwin-x86_64": {
                "signature": "${DARWIN_X64_SIG:-""}",
                "url": "https://oss.ttata.com/releases/$VERSION/darwin-x64/$DARWIN_X64_FILE"
              },
          EOF
          fi
          
          # Add macOS ARM64 platform if file exists
          if [ ! -z "$DARWIN_AARCH64_FILE" ]; then
            cat >> latest.json << EOF
              "darwin-aarch64": {
                "signature": "${DARWIN_AARCH64_SIG:-""}",
                "url": "https://oss.ttata.com/releases/$VERSION/darwin-aarch64/$DARWIN_AARCH64_FILE"
              },
          EOF
          fi
          
          # Add Windows platform (prefer MSI over EXE)
          if [ ! -z "$WINDOWS_MSI_FILE" ]; then
            cat >> latest.json << EOF
              "windows-x86_64": {
                "signature": "${WINDOWS_MSI_SIG:-""}",
                "url": "https://oss.ttata.com/releases/$VERSION/windows/$WINDOWS_MSI_FILE"
              }
          EOF
          elif [ ! -z "$WINDOWS_EXE_FILE" ]; then
            cat >> latest.json << EOF
              "windows-x86_64": {
                "signature": "${WINDOWS_EXE_SIG:-""}",
                "url": "https://oss.ttata.com/releases/$VERSION/windows/$WINDOWS_EXE_FILE"
              }
          EOF
          fi
          
          # Close the JSON structure
          cat >> latest.json << EOF
            }
          }
          EOF
          
          # Clean up trailing comma if exists
          sed -i 's/,\([[:space:]]*}[[:space:]]*}[[:space:]]*$\)/\1/' latest.json
          
          # Validate JSON format
          if jq empty latest.json 2>/dev/null; then
            echo "✓ latest.json is valid JSON"
            cat latest.json
          else
            echo "✗ latest.json is invalid JSON, fixing..."
            # Fallback: create a simple valid JSON
            cat > latest.json << EOF
          {
            "version": "$VERSION",
            "notes": "Release $VERSION",
            "pub_date": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
            "platforms": {}
          }
          EOF
          fi
          
          # Upload latest.json for updater
          aws s3 cp latest.json "s3://$CLOUDFLARE_R2_BUCKET/releases/latest.json" --endpoint-url="$CLOUDFLARE_R2_ENDPOINT"
          echo "Latest.json created and uploaded for updater"
